### ISSUE TITLE
脚本报错

### ISSUE THREAD

**Issue by anxinJ** [ours1505/qBittorrentAutoResume#1]
错误日志:
`configparser.NoOptionError: No option 'host' in section: 'qbittorrent'`
main.py里读取host，但config.ini里配的是ip

**Comment by anxinJ** [comment]
看了下代码，main.py和config.ini一致的。main.sh没作相应调整

**Comment by MiaM1ku** [comment]
感谢反馈！
#c4a8949 已修复
